### PR TITLE
chore: update deps and fix lots of clippy lints

### PR DESCRIPTION
**Pull request by grant0417**

### CODE REVIEW

**Comment by yazgoo** [comment]
is it possible to add clippy to to github workflows (I guess in ci.yml)

**Review by yazgoo — CHANGES_REQUESTED** [review]
is it possible to add clippy to to github workflows (I guess in ci.yml)

**Comment by grant0417** [comment]
@yazgoo added the CI + fixed any new lints since I made the original PR

**Comment by yazgoo** [comment]
Looks like the ci.yml is broken https://github.com/lotabout/skim/actions/runs/3299604212/workflow
don't know why the test don't show up in the PR :thinking:

**Comment by grant0417** [comment]
The CI is fixed now, had some issues with the syntax.

**Pull request merged**
